### ISSUE TITLE
Alexaの設定を変更する．

### ISSUE THREAD

**Issue by kanekou** [RyumaRyama/nkmr-cafe#4]
現在使っているAlexaはぐっしーのアカウントなので，共有アカウントに変更しみんなが使えるようにする．

**Comment by kanekou** [comment]
# やること
- [x] Alexaアカウントの変更

 # 関連issue
#1

**Comment by Momo-ASKR** [comment]
- [x] gmailアドレス作成
- [x] 新しいamazonアカウント作成
